spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://0.0.0.0:3307/bookmark
    username: root
    password: Daily12!@

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh